url: "https://arztpraxis-hermes.de" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site
title: "Arztpraxis Hermes" # the name of your site
author:
    name: Jan Hermes
description: > # '>' means to ignore newlines until the next element
    Die Homepage der Arztpraxis Hermes.

plugins:
    - jekyll-feed
    - jekyll-seo-tag 
    - jekyll-sitemap

enabled-footer: true

google_analytics: UA-162727517-1

styling:
    colors:
        default:
            base:
                # primary: '#00a087'
                primary: "rgb(104,147,238)"
                text: '#2e2e2e'
            header:
                background-color: "rgba(104, 147, 238, 0.1)"
                box-shadow: "0px 3px 3px 0px rgba(50, 50, 50, 0.2)"

            sitename:
                color: "rgba(255, 255, 255, 1)"
            info-block:
                background-color: "rgba(255, 255, 255, 0.4)"
                opacity: 1
    
    fonts:
        default: 
            base:
                style: normal
                variant: normal 
                weight: normal 
                size: 75%
                line-height: 1.8
                family: "Varela Round, sans-serif"
            heading-title:
                size: 1.6em
                line-height: 1.5em
            heading-info-block:
                size: 1.8em
                line-height: 1.41em
        
